/*
  Each plant has its own index number because I might have
  Red bell pepper (vegetable) and Black Peppercorn (salt & pepper)
*/
var plantsList = [
  [0, 'Coffee']
, [1, 'Dark Chocolate']
, [2, 'Hazelnuts']
, [3, 'Nectarine']
, [4, 'Sweet Potato']
, [5, 'Beetroot']
, [6, 'Parsnip']
, [7, 'Wheat']
, [8, 'Onion']
, [9, 'Peppercorn']
, [10, 'Carrot']
, [11, 'Cauliflower']
, [12, 'Sprouts']
, [13, 'Potato']
, [14, 'Plum']
, [15, 'Spinich']
, [16, 'Pistachios']
, [17, 'Chard']
, [18, 'Kale']
, [19, 'Oats']
, [21, 'Flax']
, [22, 'Clementine']
, [23, 'Grapes']
, [24, 'Banana']
, [25, 'Swede']
, [26, 'Radish']
, [27, 'Strawberry']
, [28, 'Apple']
, [29, 'Mushrooms']
, [30, 'Tomato']
, [31, 'Green beans']
, [32, 'Peas']
, [33, 'Cucumber']
, [34, 'Orange']
, [35, 'Tea']
, [36, 'Brazil nut']
, [37, 'Lettuce']
, [38, 'Harrico Beans']
, [39, 'Butter beans']
, [40, 'Cabbage']
, [41, 'Sweet corn']
, [42, 'Pop corn']
, [43, 'Cashews']
];
