var appCL =
  'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/30Plants/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">9th August 2023</p> '
+ '<ul><li>' + zImp + 'Added Pumpkin Seed (~different nutrients than pumpkin), and prune is a dried plum, so merged them and added Raisin with Grape.'
+ '</li><li>' + zDev + 'Removed legacy code.'
+ '</li></ul>'
  + '<hr>'
+ '<p class="B C">24th July 2023</p> '
+ '<ul><li>' + zNew + '(finally) Added how many days since start of the week.'
+ '</li><li>' + zImp + 'Plant list is a little bigger now - too small on my phone!'
+ '</li><li>' + zDev + 'Save/Load should now be more efficient.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">23rd July 2023</p> '
+ '<ul><li>' + zImp + 'Added loads more plants - should be a fairly good list now :D'
+ '</li><li>' + zImp + 'Toggle plant add/remove (in search) in case of adding wrong plant.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">20th July 2023</p> '
+ '<ul><li>' + zImp + 'Alphabetise the lists.'
+ '</li><li>' + zNew + 'Ability to add many plants in one go.'
+ '</li><li>' + zDev + 'lots of code tweaks and changes. (hopefully nothing breaks!)'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">later on 19th July 2023</p> '
+ '<ul><li>' + zImp + 'Cleaned up the plant list a bit.'
+ '</li><li>' + zDev + 'Removed local testing plant list.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">19th July 2023</p> '
+ '<ul><li>' + zNew + 'Initial release of 30 Plants! I am expecting teething problems with this as I am using updated files.'
+ '</li></ul>'
+ '<hr>'
;
